In [35]:
import torch
from einops import repeat

# scatter

## example1&2

In [14]:
out1 = torch.zeros(size=(4, 4))
index1 = torch.tensor([
    [2, 1],
    [1, 3],
    [0, 2],
    [2, 1]
])
src1 = torch.arange(1, 9).view(4, 2).type_as(out1)

In [15]:
print(src1)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [16]:
out1.scatter_(dim=1, index=index1, src=src1)

tensor([[0., 2., 1., 0.],
        [0., 3., 0., 4.],
        [5., 0., 6., 0.],
        [0., 8., 7., 0.]])

In [20]:
out2 = torch.zeros(size=(4, 4))
index2 = torch.tensor([
    [2, 1],
    [1, 3],
    [0, 2],
    [3, 0]
])

In [21]:
out2.scatter_(dim=0, index=index2, src=src1)

tensor([[5., 8., 0., 0.],
        [3., 2., 0., 0.],
        [1., 6., 0., 0.],
        [7., 4., 0., 0.]])

## example3
实现One-hot编码

In [22]:
batch = 3
vocab_size = 10

In [23]:
one_hot_vector = torch.zeros(size=(batch, vocab_size))
one_hot_index = torch.tensor([2, 5, 6])
one_hot_index = one_hot_index.unsqueeze(dim=-1)

In [24]:
one_hot_index

tensor([[2],
        [5],
        [6]])

In [33]:
src = torch.tensor([1]).type_as(one_hot_vector)
src.shape

torch.Size([1])

In [36]:
src = repeat(src, '1 -> b 1', b=batch)
src
# 要求index的维度小于src维度 所以扩充至batch=3的重复1值

tensor([[1.],
        [1.],
        [1.]])

In [39]:
one_hot_vector.scatter_(dim=1, index=one_hot_index, src=src)

tensor([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]])

# gather

## example1&2

In [40]:
input1 =  torch.tensor([
    [0, 2, 1, 0],
    [0, 3, 0, 4],
    [5, 0, 6, 0],
    [0, 8, 7, 0]
])
index1 = torch.tensor([
    [2, 1],
    [1, 3],
    [0, 2],
    [2, 1]
])

In [41]:
torch.gather(input1, dim=1, index=index1)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [42]:
input2 = torch.tensor([
    [5, 10],
    [3, 2],
    [1, 6],
    [9, 4]
])
index2 = torch.tensor([
    [2, 1],
    [1, 3],
    [0, 2],
    [3, 0],
    [3, 0]
])

In [45]:
torch.gather(input2, dim=0, index=index2)

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 9, 10],
        [ 9, 10]])